### ISSUE TITLE
Ability to stage files/buffers/hunks in project_* functions

### ISSUE THREAD

**Issue by fedoranvar** [tanvirtin/vgit.nvim#135]
Good day to you!

Is there any sense in adding ability to stage/unstage in project_* (qf or diff_preview)?

e.g.

if i'm in project_* UI, then ` :VGit buffer_hunk_stage` will stage selected file/buffer/hunk 

Thank you!

**Comment by tanvirtin** [comment]
@fedoranvar hey and thanks for the feature request. I have always had plans to eventually add hunk staging and file staging/unstaging to `project_diff_preview`.  I am not so sure how it would work on `projects_hunks_qf` though.

The biggest struggle right now is how keymaps and events are wired up within the plugin. The Neovim internal library and it's designs around autocmd and keymapping makes it challenging to add actions to buffers, since you can't really pass functions around.

I might need to redesign events in `VGit` before attempting this feature.

**Comment by Shatur** [comment]
@tanvirtin how can I do it? I tried to stage a hunk using the action, but it doesn't work.

**Comment by tanvirtin** [comment]
@Shatur stage hunk is not implemented yet. But you can execute commands such as `buffer_stage`, `buffer_unstage`, `buffer_reset`, `stage_all` and `unstage_all`

**Comment by Shatur** [comment]
@tanvirtin got it, thanks!
These command currently missing in `README.md`.
