### ISSUE TITLE
[Question] Close VGit

### ISSUE THREAD

**Issue by ovidius72** [tanvirtin/vgit.nvim#187]
I feel a bit dump but I couldn't find an ease way to close the VGit window and the Blame popup. I have to type `:` or `/` to close VGit.
I'd like to close the blame preview just pressing any keys and VGit with `q`. How can I do that ?
Thanks for this great plugin.

**Comment by tanvirtin** [comment]
Hi there, this is a good question. I actually don't provide any auto keybind in VGit, since everyone has different workflows and I am scared of rebinding a key that they are currently using.

Closing the blame preview with any key might be a bit tricky to achieve, but I'll have to see. However, closing any VGit preview with a given key should be easily possible.

I'll add this issue as a list of things that will need to be worked on, thanks!

**Comment by danielo515** [comment]
Meanwhile can you please provide more information about how to close it in the current stage?
Is it possible to bind to a buffer specific or window specific key ? What would be the command?
