### ISSUE TITLE
floating text at the next line of the first `#include` won't disappear

### ISSUE THREAD

**Issue by nyngwang** [tanvirtin/vgit.nvim#202]
### Description

<img src="https://user-images.githubusercontent.com/24765272/149710313-94cb9cf3-a8f6-486d-96df-e4acbefc2dfb.png" width="700">

- nvim --version output: 

```
NVIM v0.7.0-dev+897-g0c0469c4f
Build type: Release
```

- Operating system: 

`macOS 12.1`

**Comment by tanvirtin** [comment]
This is caused by a new feature I added called Authorship Lens, which gives you an idea about when it was last edited and how many authors there are. Current Neovim implementation of showing virtual lines on top of the files is pretty funky.

I will move the line to the bottom of the file, you can also opt out of the feature entirely as well:

```lua
authorship_code_lens = {
  enabled = false
}
```
